name: ci

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Build and publish Docker Image to GitHub Packages Registry
  # You may pin to the exact commit or the version.
  # uses: VaultVulp/gp-docker-action@6fa9f10d2b6f0080b7e21087c52db331d1f16371
        uses: VaultVulp/gp-docker-action@1.1.8
        with:
          # GitHub token to push Docker image to GitHub Packages
          github-token: ${{ secrets.GITHUB_TOKEN }}
          # Docker Image name
          image-name: modern-durak-server
          # Docker Image tag
          image-tag: latest
          # Extract git-tag from repository
          extract-git-tag: false
          # Dockerfile name
          dockerfile: Dockerfile
          # Path to build context
          build-context: .
          # Pull the image before buiding it
          pull-image: false
          # Any additional docker build arguments as a string
          #custom-args: # optional, default is 
